"""
Comfy UI Prompt Preset Selector
A simple node for selecting text presets from external files
"""

from .nodes import NODE_CLASS_MAPPINGS as _BASE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as _BASE_NAME_MAPPINGS
from .multi_source_nodes import NODE_CLASS_MAPPINGS as _MULTI_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as _MULTI_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**_BASE_MAPPINGS, **_MULTI_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**_BASE_NAME_MAPPINGS, **_MULTI_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
