[project]
name = "comfyui-prompt-preset-selector"
description = "Flexible preset selector with YAML support, advanced keyword filtering, hierarchical key search, multi-file/folder search, and subfolder organization"
version = "1.3.0"
license = {file = "LICENSE"}

classifiers = [
    "Operating System :: OS Independent",
    "Environment :: GPU :: NVIDIA CUDA",
    "Environment :: GPU :: AMD ROCm",
]

[project.urls]
Repository = "https://github.com/shin131002/ComfyUI-Prompt-Preset-Selector"

[tool.comfy]
PublisherId = "konohana"
DisplayName = "Prompt Preset Selector"
Icon = ""
